export const NIGERIAN_BANKS = [
  "Access Bank",
  "Carbon",
  "Citibank Nigeria",
  "Ecobank Nigeria",
  "Eyowo",
  "FairMoney Microfinance Bank",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "First City Monument Bank (FCMB)",
  "Globus Bank",
  "Guaranty Trust Bank (GTBank)",
  "Heritage Bank",
  "Jaiz Bank",
  "Keystone Bank",
  "Kuda Bank",
  "Lotus Bank",
  "Moniepoint Microfinance Bank",
  "Opay",
  "Optimus Bank",
  "Paga",
  "PalmPay",
  "Parallex Bank",
  "Polaris Bank",
  "PremiumTrust Bank",
  "Providus Bank",
  "Rubies Microfinance Bank",
  "Signature Bank",
  "Sparkle Microfinance Bank",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank",
  "Sterling Bank",
  "SunTrust Bank",
  "TAJBank",
  "Titan Trust Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa (UBA)",
  "Unity Bank",
  "VFD Microfinance Bank",
  "Wema Bank (ALAT)",
  "Zenith Bank",
] as const
